import { BankEntry } from '../domain/BankEntry';
import { ComplianceRepository } from '../ports/ComplianceRepository';
import { BankRepository } from '../ports/BankRepository';

export class BankSurplusUseCase {
  constructor(
    private complianceRepository: ComplianceRepository,
    private bankRepository: BankRepository
  ) {}

  async execute(shipId: string, year: number): Promise<BankEntry> {
    const compliance = await this.complianceRepository.findByShipAndYear(shipId, year);
    if (!compliance) {
      throw new Error(`Compliance balance not found for ship ${shipId} in year ${year}`);
    }

    if (compliance.cbGco2Eq <= 0) {
      throw new Error('Cannot bank non-positive compliance balance');
    }

    const bankEntry = new BankEntry(
      '', // Will be generated by repository
      shipId,
      year,
      compliance.cbGco2Eq
    );

    return this.bankRepository.save(bankEntry);
  }
}

