import { ComplianceBalance } from '../domain/ComplianceBalance';
import { ComplianceRepository } from '../ports/ComplianceRepository';
import { RouteRepository } from '../ports/RouteRepository';

const TARGET_INTENSITY = 89.3368; // gCO₂e/MJ
const ENERGY_PER_TONNE = 41000; // MJ/t

export class CalculateComplianceBalanceUseCase {
  constructor(
    private complianceRepository: ComplianceRepository,
    private routeRepository: RouteRepository
  ) {}

  async execute(shipId: string, year: number): Promise<ComplianceBalance> {
    // For simplicity, we'll use routeId as shipId
    const route = await this.routeRepository.findByRouteId(shipId);
    if (!route) {
      throw new Error(`Route/Ship ${shipId} not found`);
    }

    const energyInScope = route.fuelConsumption * ENERGY_PER_TONNE;
    const cbGco2Eq = (TARGET_INTENSITY - route.ghgIntensity) * energyInScope / 1000; // Convert to tonnes

    const compliance = new ComplianceBalance(
      '', // Will be generated by repository
      shipId,
      year,
      cbGco2Eq
    );

    return this.complianceRepository.save(compliance);
  }
}

